
import { FoodItem, Language } from './types';

export const TRANSLATIONS: Record<string, Record<Language, string>> = {
  guideTitle: { pt: "CALCULADORA", en: "CALCULATOR" },
  guideSubtitle: { pt: "DIAS FIT", en: "DIAS FIT" },
  homeDesc: { pt: "", en: "" },
  startBtn: { pt: "ACESSAR SISTEMA", en: "ACCESS SYSTEM" },
  legalTitle: { pt: "AVISO IMPORTANTE ⚠️", en: "IMPORTANT NOTICE ⚠️" },
  legalDesc: { 
    pt: "Este projeto é uma Calculadora de macro nutrientes. Ela NÃO substitui o trabalho de um nutricionista. Serve exclusivamente para levar informação e auxiliar no controle calórico baseado em dados técnicos.",
    en: "This project is a Macronutrient Calculator. It does NOT replace a nutritionist. It serves exclusively to provide information and assist in calorie control based on technical data."
  },
  proceedBtn: { pt: "ENTENDI E CONTINUAR", en: "I UNDERSTAND & CONTINUE" },
  calcTitle: { pt: "Cálculo de Necessidade Calórica", en: "Calorie Needs Calculation" },
  nextStepBtn: { pt: "O QUE FAÇO AGORA?", en: "WHAT DO I DO NOW?" },
  mealsQuestion: { pt: "Quantas refeições fará no dia?", en: "How many meals will you have today?" },
  instructionText: { pt: "AGORA COLOQUE EM CADA CAMPO OS ALIMENTOS QUE IRÁ CONSUMIR QUE EU CALCULO PRA VOCÊ!", en: "NOW ADD THE FOODS YOU WILL CONSUME IN EACH FIELD AND I'LL CALCULATE IT FOR YOU!" },
  calculateFinal: { pt: "CALCULAR", en: "CALCULATE" }
};

export const FOOD_DATABASE: FoodItem[] = [
  // PROTEÍNAS E LATICÍNIOS
  { id: '1', name: 'Ovo Inteiro', measure: 'unid', carbs: 0.3, protein: 6.3, fat: 5.0, calories: 72, category: 'Proteínas' },
  { id: '2', name: 'Clara de Ovo', measure: 'unid', carbs: 0.2, protein: 3.6, fat: 0.0, calories: 17, category: 'Proteínas' },
  { id: '3', name: 'Whey Protein (Pó)', measure: '100g', carbs: 10, protein: 73, fat: 7, calories: 395, category: 'Proteínas', minPortion: 30 },
  { id: '4', name: 'Chã de Dentro (Grelhado)', measure: '100g', carbs: 0, protein: 32, fat: 9, calories: 219, category: 'Proteínas' },
  { id: '5', name: 'Chã de Dentro (Moído)', measure: '100g', carbs: 0, protein: 30, fat: 8, calories: 205, category: 'Proteínas' },
  { id: '6', name: 'Carne Bovina (Patinho)', measure: '100g', carbs: 0, protein: 35, fat: 7, calories: 219, category: 'Proteínas' },
  { id: '7', name: 'Peito de Frango Grelhado', measure: '100g', carbs: 0, protein: 32, fat: 2.5, calories: 165, category: 'Proteínas' },
  { id: '131', name: 'Frango Desfiado', measure: '100g', carbs: 0, protein: 32, fat: 2.5, calories: 165, category: 'Proteínas' },
  { id: '8', name: 'Tilápia (Grelhada)', measure: '100g', carbs: 0, protein: 26, fat: 2.5, calories: 128, category: 'Proteínas' },
  { id: '9', name: 'Sardinha (em conserva)', measure: '100g', carbs: 0, protein: 24, fat: 12, calories: 208, category: 'Proteínas' },
  { id: '10', name: 'Fígado de Boi', measure: '100g', carbs: 5, protein: 29, fat: 5, calories: 185, category: 'Proteínas' },
  { id: '11', name: 'Filé Suíno (Lombo)', measure: '100g', carbs: 0, protein: 31, fat: 5, calories: 170, category: 'Proteínas' },
  { id: '12', name: 'Presunto Magro', measure: 'fatia', carbs: 0.4, protein: 3, fat: 0.7, calories: 20, category: 'Proteínas' },
  { id: '13', name: 'Muçarela (Queijo)', measure: 'fatia', carbs: 0.6, protein: 4.6, fat: 4.4, calories: 60, category: 'Proteínas' },
  { id: '14', name: 'Queijo Minas Frescal', measure: '100g', carbs: 3.2, protein: 17, fat: 20, calories: 260, category: 'Proteínas' },
  { id: '15', name: 'Ricota', measure: '100g', carbs: 3.8, protein: 11, fat: 8, calories: 140, category: 'Proteínas' },
  { id: '16', name: 'Iogurte Natural', measure: '100g', carbs: 5, protein: 4, fat: 3, calories: 63, category: 'Proteínas' },
  { id: '17', name: 'Iogurte Grego (Natural)', measure: '100g', carbs: 4.5, protein: 10, fat: 5, calories: 113, category: 'Proteínas' },
  { id: '18', name: 'Leite Integral', measure: '100ml', carbs: 5, protein: 3.3, fat: 3.5, calories: 60, category: 'Proteínas' },
  { id: '19', name: 'Tofu', measure: '100g', carbs: 1.9, protein: 8, fat: 4.8, calories: 76, category: 'Proteínas' },
  { id: '107', name: 'Alcatra (Grelhada)', measure: '100g', carbs: 0, protein: 31.9, fat: 11.7, calories: 241, category: 'Proteínas' },
  { id: '108', name: 'Contrafilé (Grelhado)', measure: '100g', carbs: 0, protein: 29.1, fat: 15.5, calories: 278, category: 'Proteínas' },
  { id: '109', name: 'Filé Mignon (Grelhado)', measure: '100g', carbs: 0, protein: 32.8, fat: 8.9, calories: 220, category: 'Proteínas' },
  { id: '110', name: 'Maminha (Grelhada)', measure: '100g', carbs: 0, protein: 25.1, fat: 9.8, calories: 202, category: 'Proteínas' },
  { id: '111', name: 'Fraldinha (Grelhada)', measure: '100g', carbs: 0, protein: 26.0, fat: 16.0, calories: 260, category: 'Proteínas' },
  { id: '112', name: 'Lagarto (Cozido)', measure: '100g', carbs: 0, protein: 32.9, fat: 9.1, calories: 222, category: 'Proteínas' },
  { id: '113', name: 'Músculo (Cozido)', measure: '100g', carbs: 0, protein: 31.2, fat: 6.5, calories: 194, category: 'Proteínas' },
  { id: '114', name: 'Acém (Cozido)', measure: '100g', carbs: 0, protein: 26.7, fat: 10.9, calories: 215, category: 'Proteínas' },
  { id: '115', name: 'Paleta (Cozida)', measure: '100g', carbs: 0, protein: 29.7, fat: 7.5, calories: 194, category: 'Proteínas' },
  { id: '116', name: 'Coxão Duro (Assado)', measure: '100g', carbs: 0, protein: 30.5, fat: 9.5, calories: 217, category: 'Proteínas' },
  { id: '117', name: 'Cupim (Assado)', measure: '100g', carbs: 0, protein: 22.0, fat: 25.0, calories: 330, category: 'Proteínas' },
  { id: '118', name: 'Picanha (Sem gordura)', measure: '100g', carbs: 0, protein: 28.5, fat: 12.0, calories: 235, category: 'Proteínas' },
  { id: '119', name: 'Costela Bovina (Assada)', measure: '100g', carbs: 0, protein: 22.0, fat: 28.0, calories: 360, category: 'Proteínas' },
  { id: '120', name: 'Coxa de Frango (Sem pele)', measure: '100g', carbs: 0, protein: 24.0, fat: 8.2, calories: 178, category: 'Proteínas' },
  { id: '121', name: 'Sobrecoxa (Sem pele)', measure: '100g', carbs: 0, protein: 22.5, fat: 10.8, calories: 190, category: 'Proteínas' },
  { id: '122', name: 'Asa de Frango (Com pele)', measure: '100g', carbs: 0, protein: 23.0, fat: 14.0, calories: 235, category: 'Proteínas' },
  { id: '123', name: 'Coração de Frango (Grelhado)', measure: '100g', carbs: 1, protein: 15.3, fat: 15.0, calories: 207, category: 'Proteínas' },
  { id: '124', name: 'Moela de Frango (Cozida)', measure: '100g', carbs: 0, protein: 19.0, fat: 2.1, calories: 94, category: 'Proteínas' },
  { id: '125', name: 'Sobrecoxa (Com pele/Assada)', measure: '100g', carbs: 0, protein: 24.0, fat: 17.0, calories: 255, category: 'Proteínas' },
  { id: '126', name: 'Pernil Suíno (Assado)', measure: '100g', carbs: 0, protein: 31.0, fat: 12.0, calories: 240, category: 'Proteínas' },
  { id: '127', name: 'Costelinha Suína (Assada)', measure: '100g', carbs: 0, protein: 23.0, fat: 21.0, calories: 295, category: 'Proteínas' },
  { id: '128', name: 'Copa Lombo (Grelhada)', measure: '100g', carbs: 0, protein: 27.0, fat: 13.0, calories: 235, category: 'Proteínas' },
  { id: '129', name: 'Paleta Suína (Assada)', measure: '100g', carbs: 0, protein: 26.0, fat: 14.0, calories: 245, category: 'Proteínas' },

  // PÃES, GRÃOS E RAÍZES
  { id: '20', name: 'Pão de Sal (Francês)', measure: 'unid', carbs: 29, protein: 4, fat: 1.5, calories: 150, category: 'Carboidratos' },
  { id: '21', name: 'Pão de Forma (Branco)', measure: 'fatia', carbs: 12.5, protein: 2, fat: 0.8, calories: 65, category: 'Carboidratos' },
  { id: '22', name: 'Pão de Forma Integral', measure: 'fatia', carbs: 10.7, protein: 2.4, fat: 1, calories: 61, category: 'Carboidratos' },
  { id: '23', name: 'Arroz Integral (cozido)', measure: '100g', carbs: 25, protein: 2.6, fat: 1, calories: 124, category: 'Carboidratos' },
  { id: '24', name: 'Arroz Branco (cozido)', measure: '100g', carbs: 28, protein: 2.5, fat: 0.2, calories: 128, category: 'Carboidratos' },
  { id: '25', name: 'Feijão Carioca (cozido)', measure: '100g', carbs: 14, protein: 4.8, fat: 0.5, calories: 76, category: 'Carboidratos' },
  { id: '26', name: 'Mandioca (cozida)', measure: '100g', carbs: 30, protein: 0.6, fat: 0.3, calories: 125, category: 'Carboidratos' },
  { id: '27', name: 'Batata-doce (cozida)', measure: '100g', carbs: 18, protein: 1.3, fat: 0.1, calories: 77, category: 'Carboidratos' },
  { id: '28', name: 'Batata-inglesa (cozida)', measure: '100g', carbs: 12, protein: 1.2, fat: 0.1, calories: 52, category: 'Carboidratos' },
  { id: '29', name: 'Mandioquinha (Baroa)', measure: '100g', carbs: 19, protein: 1, fat: 0.2, calories: 80, category: 'Carboidratos' },
  { id: '30', name: 'Inhame (cozido)', measure: '100g', carbs: 23, protein: 1.5, fat: 0.2, calories: 97, category: 'Carboidratos' },
  { id: '31', name: 'Cará (cozido)', measure: '100g', carbs: 28, protein: 2.3, fat: 0.1, calories: 120, category: 'Carboidratos' },
  { id: '32', name: 'Aveia (flocos)', measure: '100g', carbs: 66, protein: 14, fat: 8, calories: 390, category: 'Carboidratos' },
  { id: '33', name: 'Tapioca (goma)', measure: '100g', carbs: 54, protein: 0, fat: 0, calories: 215, category: 'Carboidratos' },
  { id: '34', name: 'Cuscuz de Milho', measure: '100g', carbs: 25, protein: 2.2, fat: 0.6, calories: 113, category: 'Carboidratos' },
  { id: '35', name: 'Quinoa (cozida)', measure: '100g', carbs: 21, protein: 4.4, fat: 1.9, calories: 120, category: 'Carboidratos' },
  { id: '36', name: 'Grão-de-bico (cozido)', measure: '100g', carbs: 27, protein: 9, fat: 2.6, calories: 164, category: 'Carboidratos' },
  { id: '37', name: 'Lentilha (cozida)', measure: '100g', carbs: 20, protein: 9, fat: 0.4, calories: 116, category: 'Carboidratos' },
  { id: '38', name: 'Milho Verde (cozido)', measure: '100g', carbs: 17, protein: 3.2, fat: 2.4, calories: 108, category: 'Carboidratos' },
  { id: '39', name: 'Ervilha (fresca)', measure: '100g', carbs: 14, protein: 5, fat: 0.4, calories: 81, category: 'Carboidratos' },
  { id: '40', name: 'Pinhão (cozido)', measure: '100g', carbs: 44, protein: 3, fat: 0.7, calories: 174, category: 'Carboidratos' },
  { id: '130', name: 'Angu (Fubá cozido)', measure: '100g', carbs: 23, protein: 2.1, fat: 0.5, calories: 104, category: 'Carboidratos' },
  { id: '132', name: 'Macarrão Branco (Cozido)', measure: '100g', carbs: 25, protein: 4.5, fat: 0.8, calories: 130, category: 'Carboidratos' },

  // FRUTAS (100g)
  { id: '41', name: 'Banana Prata', measure: '100g', carbs: 23, protein: 1.3, fat: 0.3, calories: 89, category: 'Frutas', maxPortion: 250 },
  { id: '42', name: 'Maçã (com casca)', measure: '100g', carbs: 14, protein: 0.3, fat: 0.2, calories: 52, category: 'Frutas', maxPortion: 300 },
  { id: '43', name: 'Laranja', measure: '100g', carbs: 12, protein: 0.9, fat: 0.1, calories: 47, category: 'Frutas', maxPortion: 300 },
  { id: '44', name: 'Mamão Papaia', measure: '100g', carbs: 11, protein: 0.5, fat: 0.1, calories: 43, category: 'Frutas', maxPortion: 350 },
  { id: '45', name: 'Melancia', measure: '100g', carbs: 8, protein: 0.6, fat: 0.2, calories: 30, category: 'Frutas', maxPortion: 400 },
  { id: '46', name: 'Manga', measure: '100g', carbs: 15, protein: 0.8, fat: 0.4, calories: 60, category: 'Frutas', maxPortion: 300 },
  { id: '47', name: 'Abacate', measure: '100g', carbs: 8.5, protein: 2, fat: 15, calories: 160, category: 'Gorduras' },
  { id: '48', name: 'Morango', measure: '100g', carbs: 7, protein: 0.7, fat: 0.3, calories: 30, category: 'Frutas', maxPortion: 350 },
  { id: '49', name: 'Abacaxi', measure: '100g', carbs: 13, protein: 0.5, fat: 0.1, calories: 50, category: 'Frutas', maxPortion: 300 },
  { id: '50', name: 'Limão', measure: '100g', carbs: 9, protein: 1.1, fat: 0.3, calories: 29, category: 'Frutas', maxPortion: 100 },
  { id: '51', name: 'Pera', measure: '100g', carbs: 15, protein: 0.3, fat: 0.1, calories: 57, category: 'Frutas', maxPortion: 250 },
  { id: '52', name: 'Kiwi', measure: '100g', carbs: 15, protein: 1.1, fat: 0.5, calories: 61, category: 'Frutas', maxPortion: 250 },
  { id: '53', name: 'Melão', measure: '100g', carbs: 8, protein: 0.8, fat: 0.2, calories: 34, category: 'Frutas', maxPortion: 400 },
  { id: '54', name: 'Goiaba Vermelha', measure: '100g', carbs: 14, protein: 2.6, fat: 1, calories: 68, category: 'Frutas', maxPortion: 250 },
  { id: '55', name: 'Uva Niágara', measure: '100g', carbs: 17, protein: 0.6, fat: 0.2, calories: 67, category: 'Frutas', maxPortion: 250 },
  { id: '56', name: 'Ameixa', measure: '100g', carbs: 11, protein: 0.7, fat: 0.3, calories: 46, category: 'Frutas', maxPortion: 250 },
  { id: '57', name: 'Maracujá (polpa)', measure: '100g', carbs: 23, protein: 2.2, fat: 0.7, calories: 97, category: 'Frutas', maxPortion: 150 },
  { id: '58', name: 'Tangerina/Mexerica', measure: '100g', carbs: 13, protein: 0.8, fat: 0.3, calories: 53, category: 'Frutas', maxPortion: 300 },
  { id: '59', name: 'Caju', measure: '100g', carbs: 10, protein: 0.8, fat: 0.3, calories: 43, category: 'Frutas', maxPortion: 250 },
  { id: '60', name: 'Açaí (polpa pura)', measure: '100g', carbs: 6, protein: 1, fat: 5, calories: 60, category: 'Frutas', maxPortion: 200 },
  { id: '61', name: 'Coco (fresco)', measure: '100g', carbs: 15, protein: 3.3, fat: 33, calories: 354, category: 'Gorduras' },
  { id: '62', name: 'Jabuticaba', measure: '100g', carbs: 13, protein: 0.6, fat: 0.1, calories: 58, category: 'Frutas', maxPortion: 250 },
  { id: '63', name: 'Pêssego', measure: '100g', carbs: 9, protein: 0.9, fat: 0.3, calories: 39, category: 'Frutas', maxPortion: 300 },
  { id: '64', name: 'Jaca', measure: '100g', carbs: 23, protein: 1.7, fat: 0.6, calories: 95, category: 'Frutas', maxPortion: 200 },

  // VEGETAIS E FOLHOSOS (100g)
  { id: '65', name: 'Brócolis (cozido)', measure: '100g', carbs: 4.4, protein: 2.1, fat: 0.5, calories: 25, category: 'Vegetais', maxPortion: 300 },
  { id: '66', name: 'Alface', measure: '100g', carbs: 1.7, protein: 1.3, fat: 0.2, calories: 15, category: 'Vegetais', maxPortion: 200 },
  { id: '67', name: 'Tomate', measure: '100g', carbs: 3.9, protein: 1.1, fat: 0.2, calories: 18, category: 'Vegetais', maxPortion: 300 },
  { id: '68', name: 'Abobrinha', measure: '100g', carbs: 3.0, protein: 1.1, fat: 0.1, calories: 17, category: 'Vegetais', maxPortion: 300 },
  { id: '69', name: 'Cenoura', measure: '100g', carbs: 10, protein: 1.3, fat: 0.2, calories: 41, category: 'Vegetais', maxPortion: 250 },
  { id: '70', name: 'Couve', measure: '100g', carbs: 4.3, protein: 2.9, fat: 0.5, calories: 27, category: 'Vegetais', maxPortion: 200 },
  { id: '71', name: 'Cebola', measure: '100g', carbs: 9, protein: 1.1, fat: 0.1, calories: 40, category: 'Vegetais', maxPortion: 150 },
  { id: '72', name: 'Alho', measure: '100g', carbs: 33, protein: 6.4, fat: 0.5, calories: 149, category: 'Vegetais', maxPortion: 50 },
  { id: '73', name: 'Chuchu', measure: '100g', carbs: 3.4, protein: 0.4, fat: 0.1, calories: 19, category: 'Vegetais', maxPortion: 300 },
  { id: '74', name: 'Abóbora (cozida)', measure: '100g', carbs: 11, protein: 1, fat: 0.1, calories: 48, category: 'Vegetais', maxPortion: 300 },
  { id: '75', name: 'Couve-flor', measure: '100g', carbs: 4.1, protein: 1.9, fat: 0.2, calories: 25, category: 'Vegetais', maxPortion: 300 },
  { id: '76', name: 'Espinafre', measure: '100g', carbs: 3.8, protein: 2.9, fat: 0.4, calories: 23, category: 'Vegetais', maxPortion: 250 },
  { id: '77', name: 'Rúcula', measure: '100g', carbs: 3.7, protein: 2.6, fat: 0.7, calories: 25, category: 'Vegetais', maxPortion: 150 },
  { id: '78', name: 'Repolho', measure: '100g', carbs: 5.8, protein: 1.3, fat: 0.1, calories: 25, category: 'Vegetais', maxPortion: 250 },
  { id: '79', name: 'Berinjela', measure: '100g', carbs: 4.5, protein: 0.8, fat: 0.2, calories: 20, category: 'Vegetais', maxPortion: 300 },
  { id: '80', name: 'Beterraba', measure: '100g', carbs: 10, protein: 1.7, fat: 0.2, calories: 44, category: 'Vegetais', maxPortion: 200 },
  { id: '81', name: 'Vagem', measure: '100g', carbs: 7.1, protein: 1.8, fat: 0.2, calories: 31, category: 'Vegetais', maxPortion: 200 },
  { id: '82', name: 'Pimentão', measure: '100g', carbs: 6.0, protein: 1, fat: 0.3, calories: 27, category: 'Vegetais', maxPortion: 200 },
  { id: '83', name: 'Quiabo', measure: '100g', carbs: 7, protein: 1.9, fat: 0.2, calories: 33, category: 'Vegetais', maxPortion: 200 },

  // OLEAGINOSAS E EXTRAS
  { id: '84', name: 'Castanha-do-Pará', measure: '100g', carbs: 12, protein: 14, fat: 66, calories: 656, category: 'Gorduras' },
  { id: '85', name: 'Castanha-de-caju', measure: '100g', carbs: 30, protein: 18, fat: 44, calories: 553, category: 'Gorduras' },
  { id: '86', name: 'Amendoim (torrado)', measure: '100g', carbs: 16, protein: 26, fat: 49, calories: 567, category: 'Gorduras' },
  { id: '87', name: 'Nozes', measure: '100g', carbs: 14, protein: 15, fat: 65, calories: 654, category: 'Gorduras' },
  { id: '88', name: 'Amêndoa', measure: '100g', carbs: 21, protein: 21, fat: 50, calories: 579, category: 'Gorduras' },
  { id: '89', name: 'Semente de Girassol', measure: '100g', carbs: 20, protein: 21, fat: 51, calories: 584, category: 'Gorduras' },
  { id: '90', name: 'Semente de Abóbora', measure: '100g', carbs: 10, protein: 30, fat: 49, calories: 559, category: 'Proteínas' },
  { id: '91', name: 'Chia (semente)', measure: '100g', carbs: 42, protein: 17, fat: 31, calories: 486, category: 'Carboidratos' },
  { id: '92', name: 'Linhaça', measure: '100g', carbs: 29, protein: 18, fat: 42, calories: 534, category: 'Gorduras' },
  { id: '93', name: 'Gergelim', measure: '100g', carbs: 23, protein: 18, fat: 50, calories: 573, category: 'Gorduras' },
  { id: '94', name: 'Azeite de Oliva', measure: '100g', carbs: 0, protein: 0, fat: 100, calories: 884, category: 'Gorduras' },
  { id: '95', name: 'Azeitona Preta', measure: '100g', carbs: 6, protein: 0.8, fat: 11, calories: 115, category: 'Gorduras' },
  { id: '96', name: 'Cacau em Pó', measure: '100g', carbs: 58, protein: 20, fat: 14, calories: 228, category: 'Carboidratos' },
  { id: '97', name: 'Café (sem açúcar)', measure: '100ml', carbs: 0, protein: 0.1, fat: 0, calories: 2, category: 'Vegetais' },
  
  // BEBIDAS
  { id: '98', name: 'Refrigerante Zero', measure: '100ml', carbs: 0, protein: 0, fat: 0, calories: 1, category: 'Vegetais' },
  { id: '99', name: 'Suco de Laranja (sem açúcar)', measure: '100ml', carbs: 10, protein: 0.7, fat: 0.2, calories: 45, category: 'Frutas', maxPortion: 300 },
  { id: '100', name: 'Suco de Limão (sem açúcar)', measure: '100ml', carbs: 9, protein: 1, fat: 0.2, calories: 29, category: 'Frutas', maxPortion: 300 },
  { id: '101', name: 'Suco de Morango (sem açúcar)', measure: '100ml', carbs: 8, protein: 0.4, fat: 0.2, calories: 35, category: 'Frutas', maxPortion: 300 },
  { id: '102', name: 'Suco de Uva (sem açúcar)', measure: '100ml', carbs: 14, protein: 0.3, fat: 0.1, calories: 60, category: 'Frutas', maxPortion: 300 },
  { id: '103', name: 'Suco de Abacaxi (sem açúcar)', measure: '100ml', carbs: 12, protein: 0.4, fat: 0.1, calories: 50, category: 'Frutas', maxPortion: 300 },
  { id: '104', name: 'Suco de Maracujá (sem açúcar)', measure: '100ml', carbs: 10, protein: 0.6, fat: 0.3, calories: 45, category: 'Frutas', maxPortion: 300 },
  { id: '105', name: 'Suco de Acerola (sem açúcar)', measure: '100ml', carbs: 7, protein: 0.8, fat: 0.2, calories: 32, category: 'Frutas', maxPortion: 300 },
  { id: '106', name: 'Suco de Manga (sem açúcar)', measure: '100ml', carbs: 14, protein: 0.5, fat: 0.3, calories: 60, category: 'Frutas', maxPortion: 300 },
];
